language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements_for_test.txt
  - npm install
  - npm run frontend-build:production
script:
  - PYTEST_ARGS='--cov=app --cov-report=term-missing' make test
after_success:
  - coveralls
notifications:
  email: false
